[package]
name = "archiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
bzip2 = "0.4.3"
flate2 = "1.0.25"
clap = {version = "4.0.29", features = ["derive"]}
tar = "0.4.38"
md5 = "0.7.0"
serde = "1.0.149"
serde_json = "1.0.89"
